pipeline {
    agent {
        label 'prod'
    }
    stages {
        stage ('Ip Address') {
            steps {
                sh 'hostname -I'
            }
        }
	stage ('host name') {
	    steps {
		sh 'hostname'
            }
	}
        stage ('Disk-util') {
            steps {
                sh 'df -h'
            }
        }
        stage ('memory') {
            steps {
                sh 'free -h'
            }
        }
        stage ('cpu-util') {
            steps {
                sh 'top -bn1 | head -20'
            }
        }
	stage ('list block') {
	    steps {
		sh 'lsblk'
	    }
	}
	
    }
}
