pipeline {
    agent {
        label 'prod'
    }
    stages {
        stage ('Ip Address') {
            steps {
                sh 'hostname -I'
            }
        }
        stage ('Disk-util') {
            steps {
                sh 'df -h'
            }
        }
        stage ('memory') {
            steps {
                sh 'free -h'
            }
        }
        stage ('cpu-util') {
            steps {
                sh 'top -bn1 | head -20'
            }
        }
    }
}
